dist: xenial
language: python

cache: pip

python:
  - "3.6"
  - "3.7"

# command to install dependencies
install:
  - pip install .
  - pip install pytest-cov pytest-sugar responses flake8 mypy black
# command to run tests

script:
  - black setup.py src tests --check
  - mypy src tests setup.py --ignore-missing-imports  --disallow-untyped-defs
  - flake8 setup.py src tests --exit-zero
  - pytest -vv --cov=hexpy


after_success:
  - make clean
  - pip install -e .
  - pytest -v --cov=hexpy --cov-report=xml
  - bash <(curl -s https://codecov.io/bash)
