on: [pull_request]

name: CI Build

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7]
    steps:

    - uses: actions/checkout@master

    - name: Set up Python $
      uses: actions/setup-python@master
      with:
        version: $

    - name: Install
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install pytest-cov pytest-sugar responses flake8 mypy black

    - name: Test
      run: |
        black setup.py src tests --check
        mypy src tests setup.py --ignore-missing-imports  --disallow-untyped-defs
        flake8 setup.py src tests --exit-zero
        pytest -vv --cov=hexpy

    - name: Codecov
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        make clean
        pip install -e .
        pytest -v --cov=hexpy --cov-report=xml
        bash <(curl -s https://codecov.io/bash)