on: [push]

name: Python package

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7]
    steps:

    - uses: actions/checkout@master

    - name: Set up Python $
      uses: actions/setup-python@master
      with:
        version: $

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test with pytest
      run: |
        pip install pytest
        pytest
